function pmQCModelRes = createQCModelResStuct(nexamples, nfolds)

% createQCModelResStuct - creates the model result structure for the
% quality classifier

pmQCModelRes = struct('Folds'      , [], 'LLH', 0.0        , 'Pred'       , zeros(nexamples,1), ...
                  'PredSort'   , zeros(nexamples,1)    , 'LabelSort'  , zeros(nexamples,1), ...
                  'Precision'  , zeros(nexamples,1)    , 'Recall'     , zeros(nexamples,1), ...
                  'TPR'        , zeros(nexamples,1)    , 'FPR'        , zeros(nexamples,1), ...
                  'Loss'       , zeros(nfolds, 1)      , 'AvgLoss'    , 0.0, ...
                  'PRAUC'      , 0.0                   , 'ROCAUC'     , 0.0, ...
                  'Acc'        , 0.0                   , 'PosAcc'     , 0.0, ...
                  'NegAcc'     , 0.0);

end

