clear; close all; clc;

basedir = setBaseDir();
subfolder = 'DataFiles';
basefeatureparamfile = selectBaseFeatureParameters();
basefeatureparamfile = strcat(basefeatureparamfile, '.xlsx');

pmBaseFeatureParams = readtable(fullfile(basedir, subfolder, basefeatureparamfile));

maxfeatureduration = max(pmBaseFeatureParams.featureduration);
maxnormwindow      = max(pmBaseFeatureParams.normwindow);

fprintf('Creating Feature and Label files for %2d permutations of parameters\n', size(pmBaseFeatureParams,1));
fprintf('\n');

for rp = 1:size(pmBaseFeatureParams,1)
    basefilename = generateFileNameFromBaseFeatureParams(pmBaseFeatureParams(rp,:));
    fprintf('%2d. Generating features and lables for %s\n', rp, basefilename);
    fprintf('-------------------------------------------------------------------------------\n');
    
    % load model inputs
    tic
    basedir = setBaseDir();
    subfolder = 'MatlabSavedVariables';
    modelinputsmatfile = sprintf('%s.mat',pmBaseFeatureParams.modelinputsmatfile{rp});
    fprintf('Loading model input data\n');
    load(fullfile(basedir, subfolder, modelinputsmatfile));

    toc
    fprintf('\n');
    
    % create normalisation window cube (for use with Normalisation method 3 & 4 in
    % model
    tic
    fprintf('Creating normalisation window cube\n');
    [pmMucube, pmSigmacube, pmMuNormcube, pmSigmaNormcube, pmBuckMuNormcube, pmBuckSigmaNormcube, ...
    muntilepoints, sigmantilepoints] = createPMNormWindowcube(pmPatients, pmInterpDatacube, ...
        pmOverallStats, pmPatientMeasStats, pmBaseFeatureParams.normmethod(rp), ...
        pmBaseFeatureParams.normwindow(rp), pmBaseFeatureParams.nbuckpmeas(rp),...
        npatients, maxdays, measures, nmeasures); 
    toc
    fprintf('\n');
    
    % create measures volatility cube
    tic
    fprintf('Creating volatility and segment volatility cubes\n');
    [pmInterpVolcube, mvolstats, pmInterpSegVolcube] = createPMInterpVolcube(pmPatients, pmInterpDatacube, ...
        npatients, maxdays, nmeasures, pmBaseFeatureParams.featureduration(rp), pmBaseFeatureParams.nvolseg(rp), ...
        pmBaseFeatureParams.normwindow(rp)); 
    toc
    fprintf('\n');
    
    % create measures range cube
    tic
    fprintf('Creating range and segment average measure cubes\n');
    [pmInterpRangecube, pmInterpSegAvgcube] = createPMInterpRangecube(pmPatients, pmInterpDatacube, ...
        npatients, maxdays, nmeasures, pmBaseFeatureParams.featureduration(rp), pmBaseFeatureParams.navgseg(rp), ...
        pmBaseFeatureParams.normwindow(rp)); 
    toc
    fprintf('\n');
    
    if pmBaseFeatureParams.smfunction(rp) > 0
        tic
        pmInterpDatacube = createPMInterpSmoothcube(pmInterpDatacube, pmPatients, npatients, ...
                                maxdays, measures, nmeasures, pmBaseFeatureParams.smfunction(rp), ...
                                pmBaseFeatureParams.smwindow(rp), pmBaseFeatureParams.smlength(rp));
        toc
        fprintf('\n');
    end
    
    % create bucketed data cube
    tic
    fprintf('Creating bucketed data\n');
    [pmBucketedcube, ntilepoints] = createPMBucketedcube(pmInterpDatacube, pmBaseFeatureParams.nbuckets(rp), npatients, maxdays, nmeasures); 
    toc
    fprintf('\n');
    
    % create  base feature/label examples from the data
    % need to add setting and using of the measures mask
    tic
    fprintf('Creating Base Features and Labels\n');
    [pmFeatureIndex, pmMuIndex, pmSigmaIndex, pmRawMeasFeats, pmBuckMeasFeats, pmRangeFeats, pmVolFeats, ...
        pmAvgSegFeats, pmVolSegFeats, pmCChangeFeats, pmPMeanFeats, pmPStdFeats, ...
        pmBuckPMeanFeats, pmBuckPStdFeats, pmDateFeats, pmDemoFeats, ...
        pmIVLabels, pmABLabels, pmExLabels, pmExLBLabels, pmExABLabels, pmExABxElLabels] ...
        = createBaseFeaturesAndLabelsFcn(pmPatients, pmAntibiotics, pmAMPred, ...
            pmInterpDatacube, pmInterpVolcube, pmInterpSegVolcube, ...
            pmInterpRangecube, pmInterpSegAvgcube, pmBucketedcube, ...
            pmMuNormcube, pmSigmaNormcube, pmBuckMuNormcube, pmBuckSigmaNormcube, ...
            pmMucube, pmSigmacube, ...
            measures, nmeasures, npatients, maxdays, ...
            maxfeatureduration, maxnormwindow, pmBaseFeatureParams(rp,:));
    toc
    fprintf('\n');
    
    % save output variables
    tic
    basedir = setBaseDir();
    subfolder = 'MatlabSavedVariables';
    outputfilename = sprintf('%s.mat',basefilename);
    fprintf('Saving output variables to file %s\n', outputfilename);
    save(fullfile(basedir, subfolder, outputfilename), ...
        'studynbr', 'studydisplayname', 'pmStudyInfo', ...
        'pmPatients', 'npatients', 'pmAntibiotics', 'pmAMPred', ...
        'pmOverallStats', 'pmPatientMeasStats', ...
        'pmRawDatacube', 'pmInterpDatacube',  ...
        'maxdays', 'measures', 'nmeasures', 'ntilepoints', ...
        'pmBaseFeatureParams', 'rp', ...
        'pmMucube', 'pmSigmacube', 'pmMuNormcube', 'pmSigmaNormcube', ...
        'pmBuckMuNormcube', 'pmBuckSigmaNormcube', 'muntilepoints', 'sigmantilepoints', ...
        'pmBucketedcube', 'pmInterpVolcube', 'mvolstats', 'pmInterpSegVolcube', ...
        'pmInterpRangecube', 'pmInterpSegAvgcube', ...
        'pmFeatureIndex', 'pmMuIndex', 'pmSigmaIndex', ...
        'pmRawMeasFeats', 'pmBuckMeasFeats', 'pmRangeFeats', 'pmVolFeats', ...
        'pmAvgSegFeats', 'pmVolSegFeats', 'pmCChangeFeats', ...
        'pmPMeanFeats', 'pmPStdFeats', 'pmBuckPMeanFeats', 'pmBuckPStdFeats', ...
        'pmDateFeats', 'pmDemoFeats', ...
        'pmIVLabels', 'pmABLabels', 'pmExLabels', 'pmExLBLabels', 'pmExABLabels', 'pmExABxElLabels');
    outputfilename = strrep(outputfilename, 'df3', 'df0');
    outputfilename = strrep(outputfilename, 'df1', 'df0');
    fprintf('Saving output variables to file %s\n', outputfilename);
    save(fullfile(basedir, subfolder, outputfilename), ...
        'studynbr', 'studydisplayname', 'pmStudyInfo', ...
        'pmPatients', 'npatients', 'pmAntibiotics', 'pmAMPred', ...
        'pmOverallStats', 'pmPatientMeasStats', ...
        'pmRawDatacube', 'pmInterpDatacube',  ...
        'maxdays', 'measures', 'nmeasures', 'ntilepoints', ...
        'pmBaseFeatureParams', 'rp', ...
        'pmMucube', 'pmSigmacube', 'pmMuNormcube', 'pmSigmaNormcube', ...
        'pmBuckMuNormcube', 'pmBuckSigmaNormcube', 'muntilepoints', 'sigmantilepoints', ...
        'pmBucketedcube', 'pmInterpVolcube', 'mvolstats', 'pmInterpSegVolcube', ...
        'pmInterpRangecube', 'pmInterpSegAvgcube', ...
        'pmFeatureIndex', 'pmMuIndex', 'pmSigmaIndex', ...
        'pmRawMeasFeats', 'pmBuckMeasFeats', 'pmRangeFeats', 'pmVolFeats', ...
        'pmAvgSegFeats', 'pmVolSegFeats', 'pmCChangeFeats', ...
        'pmPMeanFeats', 'pmPStdFeats', 'pmBuckPMeanFeats', 'pmBuckPStdFeats', ...
        'pmDateFeats', 'pmDemoFeats', ...
        'pmIVLabels', 'pmABLabels', 'pmExLabels', 'pmExLBLabels', 'pmExABLabels', 'pmExABxElLabels');
    toc
    fprintf('\n');
end

beep on;
beep;

