function [pmMissPattIndex, pmMissPattFeats, pmMissPattQS, pmMissPattQSPct] = createDWMissPattTables(nmisspatts, nrawmeasures, datawinduration)

% createDWMissPattTables - creates the missingness pattern tables

pmMissPattIndex = table('Size',[nmisspatts, 8], ...
    'VariableTypes', {'double', 'cell', 'cell', 'double', 'double', 'double', 'double', 'double'}, ...
    'VariableNames', {'ScenType', 'Scenario', 'Measure', 'Frequency', 'Percentage', 'MSExample', 'MSPct', 'QCFold'});

pmMissPattFeats = zeros(nmisspatts, (datawinduration * nrawmeasures));

pmMissPattQS    = table('Size',[nmisspatts, 10], ...
                'VariableTypes', {'double', 'double', 'double', 'double', 'double',...
                                  'double', 'double', 'double', 'double', 'double'}, ...
                'VariableNames', {'PScore', 'ElecPScore', 'AvgEpiTPred', 'AvgEpiFPred', 'AvgEPV', ...
                                  'PRAUC', 'ROCAUC', 'Acc', 'PosAcc', 'NegAcc'});
                              
pmMissPattQSPct = table('Size',[nmisspatts, 10], ...
                'VariableTypes', {'double', 'double', 'double', 'double', 'double',...
                                  'double', 'double', 'double', 'double', 'double'}, ...
                'VariableNames', {'PScore', 'ElecPScore', 'AvgEpiTPred', 'AvgEpiFPred', 'AvgEPV', ...
                                  'PRAUC', 'ROCAUC', 'Acc', 'PosAcc', 'NegAcc'});

end

