    function pmQCModelRes = createQCModelResStruct(nexamples, nfolds)

% createQCModelResStruct - creates the model result structure for the
% quality classifier

pmQCModelRes = struct('Folds'      , [], 'LLH', 0.0     , 'Pred'       , zeros(nexamples,1), ...
                  'PredSort'    , zeros(nexamples,1)    , 'LabelSort'  , zeros(nexamples,1), ...
                  'FPLabelSort' , zeros(nexamples,1)    , ...
                  'TP'          , zeros(nexamples,1)    , 'TN'         , zeros(nexamples,1), ...
                  'FP'          , zeros(nexamples,1)    , 'FN'         , zeros(nexamples,1), ...
                  'FP1'         , zeros(nexamples,1)    , 'FP2'        , zeros(nexamples,1), ...
                  'Precision'   , zeros(nexamples,1)    , 'Recall'     , zeros(nexamples,1), ...
                  'TPR'         , zeros(nexamples,1)    , 'FPR'        , zeros(nexamples,1), ...
                  'QCCostArray' , zeros(nexamples,1)    , ...
                  'Loss'        , zeros(nfolds, 1)      , 'AvgLoss'    , 0.0, ...
                  'PRAUC'       , 0.0                   , 'ROCAUC'     , 0.0, ...
                  'Acc'         , 0.0                   , 'PosAcc'     , 0.0, ...
                  'NegAcc'      , 0.0                   , ...
                  'IdxOp'       , 0.0                   , 'PredOp'     , 0.0, ...
                  'TPROp'       , 0.0                   , 'FPROp'      , 0.0, ...
                  'PrecisionOp' , 0.0                   , 'RecallOp'   , 0.0, ...
                  'QCCostOp'    , 0.0);

end

