function [pmFeatureIndex, pmDataWindowArray, pmExABxElLabels] ...
            = createDataWindowArrays(nexamples, nmeasures, totalduration)
    
pmFeatureIndex = table('Size',[nexamples, 12], ...
    'VariableTypes', {'double', 'cell', 'double', 'datetime', 'double', 'double', ...
                      'cell', 'double', 'cell', 'double', 'double', 'double'}, ...
    'VariableNames', {'PatientNbr', 'Study', 'ID', 'CalcDate', 'CalcDatedn', 'ScenType', ...
                      'Scenario', 'BaseExample', 'Measure', 'Frequency', 'Percentage', 'MSExample'});

pmDataWindowArray   = nan(nexamples, totalduration, nmeasures);

pmExABxElLabels    = false(nexamples, 1);

end

