function [pmMissPattIndex, pmMissPattArray, pmMissPattQS] = createMissPattTables(nmisspatts, nrawfeatures)

% createMissPattTables - creates the missingness pattern tables

pmMissPattIndex = table('Size',[nmisspatts, 6], ...
    'VariableTypes', {'double', 'cell', 'cell', 'double', 'double', 'double'}, ...
    'VariableNames', {'ScenType', 'Scenario', 'Measure', 'Frequency', 'Percentage', 'MSExample'});

pmMissPattArray = zeros(nmisspatts, nrawfeatures);

pmMissPattQS = table('Size',[nmisspatts, 10], ...
                'VariableTypes', {'double', 'double', 'double', 'double', 'double',...
                                  'double', 'double', 'double', 'double', 'double'}, ...
                'VariableNames', {'PScore', 'ElecPScore', 'AvgEpiTPred', 'AvgEpiFPred', 'AvgEPV', ...
                                  'PRAUC', 'ROCAUC', 'Acc', 'PosAcc', 'NegAcc'});

end

