function [hyperparamQS, hyperparamqsrow, foldhpTrQS, foldhpCVQS, foldhprow] = createHpQSTables(nhpcomb)

% createHpQSTables - creates the tables to store the hyper parameter QS
% results

hyperparamQS = table('Size',[nhpcomb, 20], ...
                'VariableTypes', {'double', 'double', 'double', 'double', 'double', ...
                                  'double', 'double', 'double', 'double', 'double', 'double',...
                                  'double', 'double', 'double', 'double', 'double', ...
                                  'double', 'double', 'double', 'double'}, ...
                'VariableNames', {'LearnRate', 'NumTrees', 'MinLeafSize', 'MaxNumSplit', 'FracVarsToSample', ...
                                  'AvgLoss', 'PScore', 'ElecPScore', 'AvgEpiTPred', 'AvgEpiFPred', 'AvgEPV', ...
                                  'PRAUC', 'ROCAUC', 'Acc', 'PosAcc', 'NegAcc', ...
                                  'MaxNumNodes', 'AvgNumNodes', 'MaxBranchNodes', 'AvgBranchNodes'});
hyperparamqsrow = hyperparamQS(1, :);

temp = array2table(1);
temp.Properties.VariableNames{'Var1'} = 'Fold';
foldhpTrQS = [temp, hyperparamQS(1, :)];
foldhprow = foldhpTrQS;
foldhpTrQS(1,:) = [];
foldhpCVQS = foldhpTrQS;

end

