function ovmsTestQS = createOvMSQSTable(nmsscenarios)

% createOvMSQSTable - creates a table to store the results from missingness
% analysis

ovmsTestQS = table('Size',[nmsscenarios, 32], ...
                'VariableTypes', {'double', 'double', 'double', 'cell',   'double', 'double', 'double', ...
                                  'cell', 'cell', 'double', 'double', 'double', ...
                                  'double', 'double', 'double', 'double', 'double', ...
                                  'double', 'double', 'double', ...
                                  'double', 'double', 'double', ...
                                  'double', 'double', 'double', ...
                                  'double', 'double', 'double', ...
                                  'double', 'double', 'double'}, ...
                'VariableNames', {'ScenarioNbr', 'ScenarioType', 'MMask', 'MMaskText', 'Frequency', 'Duration', 'Percentage', ...
                                  'PScore', 'ElecPScore', 'AvgEPV', 'AvgEpiTPred', 'AvgEpiFPred', ...
                                  'PRAUC', 'ROCAUC', 'Acc', 'PosAcc', 'NegAcc', ...
                                  'PRAUC_AvR', 'PRAUCBestR', 'PRAUCWorstR', ...
                                  'ROCAUC_AvR', 'ROCAUCBestR', 'ROCAUCWorstR', ...
                                  'Acc_AvR', 'AccBestR', 'AccWorstR', ...
                                  'PosAcc_AvR', 'PosAccBestR', 'PosAccWorstR', ...
                                  'NegAcc_AvR', 'NegAccBestR', 'NegAccWorstR'});

end

