function [pmSignal] = createSignalTable(nrows)

% createBreatheScoreTable - function to create the table to hold the
% ingested breathe scores for the ACE-CF study

pmSignal = table('Size',[nrows, 14], ...
                'VariableTypes', {'double',       'cell',          'double',      'cell',         ...
                                  'cell',         'cell',          'cell',        'cell',         ...
                                  'datetime',     'double',        'double',      'double',       ...
                                  'double',       'cell'},         ...
                'VariableNames', {'PatientNbr',   'Study',         'SmartCareID',   'StudyNumber', ...
                                  'StudyNumber2', 'Hospital',      'PartitionKey',  'CalcDate',    ...
                                  'CalcDatedt',   'CalcDatedn',    'RelCalcDatedn', 'PredScore',   ...
                                  'SafetyScore', 'SignalState'});

end

