function [basefilename] = generateFileNameFromFeatureParams(pmFeatureParamRow)

% generateFileNameFromFeatureParams - generates the base file name from a
% set of feature parameters

basefilename = sprintf('pmfp_%s_st%s_fd%d_pd%d_mm%d_nm%d_bf%d_nb%d_sm%d_mx%d_vo%d', ...
        pmFeatureParamRow.Version{1},          pmFeatureParamRow.StudyDisplayName{1}, ...
        pmFeatureParamRow.featureduration,     pmFeatureParamRow.predictionduration,  ...
        pmFeatureParamRow.measuresmask,        pmFeatureParamRow.normmethod, ...
        pmFeatureParamRow.bucketfeat,          pmFeatureParamRow.nbuckets, ...
        pmFeatureParamRow.smoothingmethod,     pmFeatureParamRow.minmaxfeat, ...
        pmFeatureParamRow.volfeat);
    
end

