function [basefilename] = generateFileNameFromRunParameters(pmRunParametersRow)

% generateFileNameFromRunParameters - generates the base file name from a
% set of run parameters

basefilename = sprintf('pm_st%s_fd%d_pd%d_mm%d_nm%d_sm%d_cm%.2f_mx%d_vo%d_tp%0.2f', ...
        pmRunParametersRow.StudyDisplayName{1}, pmRunParametersRow.featureduration, ...
        pmRunParametersRow.predictionduration, pmRunParametersRow.measuresmask, ...
        pmRunParametersRow.normmethod, pmRunParametersRow.smoothingmethod, ...
        pmRunParametersRow.costmethod, pmRunParametersRow.minmaxfeat, ...
        pmRunParametersRow.volfeat, pmRunParametersRow.trainpct);
    
end

