function [outputfilename] = generateFileNameFromFullFeatureParams(pmFeatureParamsRow)

% generateFileNameFromFullFeatureParams - generates the file name from a
% full set of feature parameters

outputfilename = sprintf('pmfp%sst%sfd%dff%dpd%dnm%dnw%dsf%dsw%dsl%drm%dms%dbf%dnb%drn%dvo%das%dna%dvs%dnv%dcc%dpm%dps%dbm%dbs%dnp%ddf%ddm%d', ...
        pmFeatureParamsRow.FeatVer{1},          pmFeatureParamsRow.StudyDisplayName{1}, ...
        pmFeatureParamsRow.featureduration,     pmFeatureParamsRow.featfreq, ...
        pmFeatureParamsRow.predictionduration,  pmFeatureParamsRow.normmethod, ...
        pmFeatureParamsRow.normwindow,          pmFeatureParamsRow.smfunction, ...
        pmFeatureParamsRow.smwindow,            pmFeatureParamsRow.smlength, ...
        pmFeatureParamsRow.rawmeasfeat,         pmFeatureParamsRow.msfeat, ...
        pmFeatureParamsRow.bucketfeat, ...
        pmFeatureParamsRow.nbuckets,            pmFeatureParamsRow.rangefeat, ...
        pmFeatureParamsRow.volfeat,             pmFeatureParamsRow.avgsegfeat, ...
        pmFeatureParamsRow.navgseg,             pmFeatureParamsRow.volsegfeat, ...
        pmFeatureParamsRow.nvolseg,             pmFeatureParamsRow.cchangefeat, ...
        pmFeatureParamsRow.pmeanfeat,           pmFeatureParamsRow.pstdfeat, ...
        pmFeatureParamsRow.buckpmean,           pmFeatureParamsRow.buckpstd, ...
        pmFeatureParamsRow.nbuckpmeas, ...
        pmFeatureParamsRow.datefeat,            pmFeatureParamsRow.demofeat);
    
     
    
end

