function plotPRAndROCCurvesForPaper(pmModelRes, pmFeatureParamsRow, lbdisplayname, ...
    plotsubfolder, basefilename)

% plotPRAndROCCurvesForPaper - plots PR and ROC curves for the model
% results formatted as a figure for the paper

titlefontsize = 14;
labelfontsize = 12;
axisfontsize = 10;
unitfontsize = 10;

widthinch = 8.25;
heightinch = 3;
name = '';
singlehght = 1/3.5;
halfhght = singlehght * 0.5;
doublehght = singlehght * 2;
twoandhalfhght = singlehght * 2.5;
triplehght = singlehght * 3;
plotwidth  = 1/3;

ntitles = 1;
nplots = 3;

typearray = [1, 3, 4, 5];

typehght = [halfhght, halfhght, triplehght, triplehght, triplehght];

baseplotname1 = sprintf('%s-QSfP', basefilename);

n = 1;
%[pmRandomRes] = generateRandomPRAndROCResults(pmModelRes.pmNDayRes(n).LabelSort);
randomprec = sum(pmModelRes.pmNDayRes(n).LabelSort) / size(pmModelRes.pmNDayRes(n).LabelSort, 1);
xl = [0 1];
yl = [0 1];

[f, p] = createFigureAndPanelForPaper(name, widthinch, heightinch);

currhght = 1.0;
currplot = 1;
for i = 1:(ntitles + nplots)
    type = typearray(i);
    if type == 1 || type == 2
        % title for three plots
        currhght = currhght - typehght(type);
        sp(i) = uipanel('Parent', p, ...
                        'BorderType', 'none', ...
                        'BackgroundColor', 'white', ...
                        'OuterPosition', [0, currhght, 1, typehght(type)]);
        displaytext = 'PR Curve';
        annotation(sp(i), 'textbox',  ...
                        'String', displaytext, ...
                        'Interpreter', 'tex', ...
                        'Units', 'normalized', ...
                        'Position', [0, 0, plotwidth, 1], ...
                        'HorizontalAlignment', 'center', ...
                        'VerticalAlignment', 'bottom', ...
                        'LineStyle', 'none', ...
                        'FontSize', labelfontsize, ...
                        'FontWeight', 'bold');
        displaytext = 'ROC Curve';
        annotation(sp(i), 'textbox',  ...
                        'String', displaytext, ...
                        'Interpreter', 'tex', ...
                        'Units', 'normalized', ...
                        'Position', [plotwidth, 0, plotwidth, 1], ...
                        'HorizontalAlignment', 'center', ...
                        'VerticalAlignment', 'bottom', ...
                        'LineStyle', 'none', ...
                        'FontSize', labelfontsize, ...
                        'FontWeight', 'bold');
    elseif type == 3
        % ROC Curve plot
        currhght = currhght - typehght(type);
        sp(i) = uipanel('Parent', p, ...
                        'BorderType', 'none', ...
                        'BackgroundColor', 'white', ...
                        'OuterPosition', [0, currhght, plotwidth, typehght(type)]);
                    
        ax = subplot(1, 1, 1, 'Parent', sp(i));

        area(ax, pmModelRes.pmNDayRes(n).Recall, pmModelRes.pmNDayRes(n).Precision, ...
            'FaceColor', 'blue', 'LineStyle', '-', 'LineWidth', 1.5);

        line(ax, [0, 1], [randomprec, randomprec], ...
            'Color', 'red', 'LineStyle', '-', 'LineWidth', 1.0);
        ax.FontSize = axisfontsize; 
        ax.TickDir = 'out';     
        xlim(ax, xl);
        ylim(ax, yl);
        
        xlabel(ax, 'Recall');
        ylabel(ax, 'Precision');

        prtext = sprintf('AUC = %.2f%%', pmModelRes.pmNDayRes(n).PRAUC);
        annotation(sp(i), 'textbox',  ...
                        'String', prtext, ...
                        'Interpreter', 'tex', ...
                        'Units', 'normalized', ...
                        'Position', [0.5, 0.7, 0.38, 0.1], ...
                        'HorizontalAlignment', 'center', ...
                        'VerticalAlignment', 'middle', ...
                        'BackgroundColor', 'white', ...
                        'LineStyle', '-', ...
                        'FontSize', axisfontsize);
        
    elseif type == 4
        % PR Curve plot
        sp(i) = uipanel('Parent', p, ...
                        'BorderType', 'none', ...
                        'BackgroundColor', 'white', ...
                        'OuterPosition', [plotwidth, currhght, plotwidth, typehght(type)]);
                    
        ax = subplot(1, 1, 1, 'Parent', sp(i));
        
        area(ax, pmModelRes.pmNDayRes(n).FPR, pmModelRes.pmNDayRes(n).TPR, ...
            'FaceColor', 'blue', 'LineStyle', '-', 'LineWidth', 1.5);
        %line(ax, pmRandomRes.FPR, pmRandomRes.FPR, ...
        %    'Color', 'red', 'LineStyle', '-', 'LineWidth', 1.5);
        line(ax, [0, 1], [0, 1], ...
            'Color', 'red', 'LineStyle', '-', 'LineWidth', 1.0);
        
        ax.FontSize = axisfontsize; 
        ax.TickDir = 'out';      
        xlim(ax, xl);
        ylim(ax, yl);
        
        xlabel(ax, 'FPR');
        ylabel(ax, 'TPR');
        
        roctext = sprintf('AUC = %.2f%%', pmModelRes.pmNDayRes(n).ROCAUC);
        annotation(sp(i), 'textbox',  ...
                        'String', roctext, ...
                        'Interpreter', 'tex', ...
                        'Units', 'normalized', ...
                        'Position', [0.5, 0.3 0.38, 0.1], ...
                        'HorizontalAlignment', 'center', ...
                        'VerticalAlignment', 'middle', ...
                        'BackgroundColor', 'white', ...
                        'LineStyle', '-', ...
                        'FontSize', axisfontsize);
    end
end

basedir = setBaseDir();
savePlotInDir(f, baseplotname1, basedir, plotsubfolder);
savePlotInDirAsSVG(f, baseplotname1, plotsubfolder);
close(f);

end

