function plotModelQualityScoresForPaper(pmTrCVFeatureIndex, pmModelRes, pmTrCVExABLabels, pmAMPred, plotsubfolder, basefilename, epilen)

% plotModelQualityScoresForPaper - calculates model quality scores at
% episode level and also how much earlier predictions are vs current
% clinical practice

[avgdelayreduction] = calcAvgDelayReduction(pmAMPred, pmTrCVFeatureIndex, pmTrCVExABLabels, pmModelRes.pmNDayRes(1).Pred);
[~, ~, ~, fpr, ~, ~] = calcQualScores(pmTrCVExABLabels, pmModelRes.pmNDayRes(1).Pred);

[epiindex, epilabl, epipred] = convertResultsToEpisodes(pmTrCVFeatureIndex, pmTrCVExABLabels, pmModelRes.pmNDayRes(1).Pred, epilen);

[epiprecision, epirecall, epitpr, epifpr, epiprauc, epirocauc] = calcQualScores(epilabl, epipred);

titlefontsize = 14;
labelfontsize = 12;
axisfontsize = 10;
unitfontsize = 10;

widthinch = 8.25;
heightinch = 3;
name = '';
singlehght = 1/3.5;
halfhght = singlehght * 0.5;
doublehght = singlehght * 2;
twoandhalfhght = singlehght * 2.5;
triplehght = singlehght * 3;
plotwidth  = 1/3;

ntitles = 1;
nplots = 3;

typearray = [1, 3, 4, 5];

typehght = [halfhght, halfhght, triplehght, triplehght, triplehght];

baseplotname1 = sprintf('%s - EpiLen %d Quality Scores for Paper', basefilename, epilen);

n = 1;
randomprec = sum(epilabl) / size(epilabl, 1);
xl = [0 1];
yl = [0 1];

[f, p] = createFigureAndPanelForPaper(name, widthinch, heightinch);

currhght = 1.0;
currplot = 1;
for i = 1:(ntitles + nplots)
    type = typearray(i);
    if type == 1 || type == 2
        % title for three plots
        currhght = currhght - typehght(type);
        sp(i) = uipanel('Parent', p, ...
                        'BorderType', 'none', ...
                        'BackgroundColor', 'white', ...
                        'OuterPosition', [0, currhght, 1, typehght(type)]);
        displaytext = 'Episode PR Curve';
        annotation(sp(i), 'textbox',  ...
                        'String', displaytext, ...
                        'Interpreter', 'tex', ...
                        'Units', 'normalized', ...
                        'Position', [0, 0, plotwidth, 1], ...
                        'HorizontalAlignment', 'center', ...
                        'VerticalAlignment', 'bottom', ...
                        'LineStyle', 'none', ...
                        'FontSize', labelfontsize, ...
                        'FontWeight', 'bold');
        displaytext = 'Episode ROC Curve';
        annotation(sp(i), 'textbox',  ...
                        'String', displaytext, ...
                        'Interpreter', 'tex', ...
                        'Units', 'normalized', ...
                        'Position', [plotwidth, 0, plotwidth, 1], ...
                        'HorizontalAlignment', 'center', ...
                        'VerticalAlignment', 'bottom', ...
                        'LineStyle', 'none', ...
                        'FontSize', labelfontsize, ...
                        'FontWeight', 'bold');
        displaytext = 'Reduction in Delay';
        annotation(sp(i), 'textbox',  ...
                        'String', displaytext, ...
                        'Interpreter', 'tex', ...
                        'Units', 'normalized', ...
                        'Position', [plotwidth * 2, 0, plotwidth, 1], ...
                        'HorizontalAlignment', 'center', ...
                        'VerticalAlignment', 'bottom', ...
                        'LineStyle', 'none', ...
                        'FontSize', labelfontsize, ...
                        'FontWeight', 'bold'); 
    elseif type == 3
        % ROC Curve plot
        currhght = currhght - typehght(type);
        sp(i) = uipanel('Parent', p, ...
                        'BorderType', 'none', ...
                        'BackgroundColor', 'white', ...
                        'OuterPosition', [0, currhght, plotwidth, typehght(type)]);
                    
        ax = subplot(1, 1, 1, 'Parent', sp(i));

        area(ax, epirecall, epiprecision, ...
            'FaceColor', 'blue', 'LineStyle', '-', 'LineWidth', 1.5);

        line(ax, [0, 1], [randomprec, randomprec], ...
            'Color', 'red', 'LineStyle', '-', 'LineWidth', 1.0);
        ax.FontSize = axisfontsize; 
        ax.TickDir = 'out';     
        xlim(ax, xl);
        ylim(ax, yl);
        
        xlabel(ax, 'Recall');
        ylabel(ax, 'Precision');

        prtext = sprintf('AUC = %.2f%%', epiprauc);
        annotation(sp(i), 'textbox',  ...
                        'String', prtext, ...
                        'Interpreter', 'tex', ...
                        'Units', 'normalized', ...
                        'Position', [0.5, 0.7, 0.38, 0.1], ...
                        'HorizontalAlignment', 'center', ...
                        'VerticalAlignment', 'middle', ...
                        'BackgroundColor', 'white', ...
                        'LineStyle', '-', ...
                        'FontSize', axisfontsize);
        
    elseif type == 4
        % PR Curve plot
        sp(i) = uipanel('Parent', p, ...
                        'BorderType', 'none', ...
                        'BackgroundColor', 'white', ...
                        'OuterPosition', [plotwidth, currhght, plotwidth, typehght(type)]);
                    
        ax = subplot(1, 1, 1, 'Parent', sp(i));
        
        area(ax, epifpr, epitpr, ...
            'FaceColor', 'blue', 'LineStyle', '-', 'LineWidth', 1.5);
        line(ax, [0, 1], [0, 1], ...
            'Color', 'red', 'LineStyle', '-', 'LineWidth', 1.0);
        
        ax.FontSize = axisfontsize; 
        ax.TickDir = 'out';      
        xlim(ax, xl);
        ylim(ax, yl);
        
        xlabel(ax, 'FPR');
        ylabel(ax, 'TPR');
        
        roctext = sprintf('AUC = %.2f%%', epirocauc);
        annotation(sp(i), 'textbox',  ...
                        'String', roctext, ...
                        'Interpreter', 'tex', ...
                        'Units', 'normalized', ...
                        'Position', [0.5, 0.3 0.38, 0.1], ...
                        'HorizontalAlignment', 'center', ...
                        'VerticalAlignment', 'middle', ...
                        'BackgroundColor', 'white', ...
                        'LineStyle', '-', ...
                        'FontSize', axisfontsize);
    elseif type == 5
        % Reduction in treatment delay plot
        sp(i) = uipanel('Parent', p, ...
                        'BorderType', 'none', ...
                        'BackgroundColor', 'white', ...
                        'OuterPosition', [plotwidth * 2, currhght, plotwidth, typehght(type)]);
                    
        ax = subplot(1, 1, 1, 'Parent', sp(i));
        
        area(ax, fpr, avgdelayreduction, ...
            'FaceColor', 'blue', 'LineStyle', '-', 'LineWidth', 1.5);
        
        ax.FontSize = axisfontsize; 
        ax.TickDir = 'out';      
        xlim(ax, xl);
        %ylim(ax, yl);
        
        xlabel(ax, 'FPR');
        ylabel(ax, 'Avg Delay Reduction');
        
        %roctext = sprintf('AUC = %.2f%%', epirocauc);
        %annotation(sp(i), 'textbox',  ...
        %                'String', roctext, ...
        %                'Interpreter', 'tex', ...
        %                'Units', 'normalized', ...
        %                'Position', [0.5, 0.3 0.38, 0.1], ...
        %                'HorizontalAlignment', 'center', ...
        %                'VerticalAlignment', 'middle', ...
        %                'BackgroundColor', 'white', ...
        %                'LineStyle', '-', ...
        %                'FontSize', axisfontsize);
    end
end

basedir = setBaseDir();
savePlotInDir(f, baseplotname1, basedir, plotsubfolder);
savePlotInDirAsSVG(f, baseplotname1, plotsubfolder);
close(f);

end

