function plotMissQSByMeasPlotFcn(ax, xdata, ydata, qsthreshold, fpthreshold, ...
            qsmeasure, meas, tpidx, fp1idx, fp2idx, tnidx, fnidx)
        
% plotMissQSBtMeasPlotFcn - convenience function to plot the QS vs
% missingness points, appropriately colourcoded.

labelfontsize = 8;
markersize = 10;
transparency = 0.2;

tpcol = 'green';
fp1col = [1.0 0.5 0];
fp2col = 'red';
tncol = [0.5 0.5 0.5];
fncol = 'blue';

hold on;
scatter(ax, xdata(tpidx), ydata(tpidx), markersize, ...
    'Marker', 'o', ...
    'MarkerEdgeColor', tpcol, ...
    'MarkerFaceColor', tpcol, ...
    'Marker', 'o', ...
    'MarkerEdgeAlpha', transparency, ...
    'MarkerFaceAlpha', transparency);
scatter(ax, xdata(tnidx), ydata(tnidx), markersize, ...
    'MarkerEdgeColor', tncol, ...
    'MarkerFaceColor', tncol, ...
    'Marker', 'o', ...
    'MarkerEdgeAlpha', transparency, ...
    'MarkerFaceAlpha', transparency);
scatter(ax, xdata(fp1idx), ydata(fp1idx), markersize, ...
    'MarkerEdgeColor', fp1col, ...
    'MarkerFaceColor', fp1col, ...
    'Marker', 'o', ...
    'MarkerEdgeAlpha', transparency, ...
    'MarkerFaceAlpha', transparency);
scatter(ax, xdata(fp2idx), ydata(fp2idx), markersize, ...
    'MarkerEdgeColor', fp2col, ...
    'MarkerFaceColor', fp2col, ...
    'Marker', 'o', ...
    'MarkerEdgeAlpha', transparency, ...
    'MarkerFaceAlpha', transparency);
scatter(ax, xdata(fnidx), ydata(fnidx), markersize, ...
    'MarkerEdgeColor', fncol, ...
    'MarkerFaceColor', fncol, ...
    'Marker', 'o', ...
    'MarkerEdgeAlpha', transparency, ...
    'MarkerFaceAlpha', transparency);
line(ax, [0 100], [qsthreshold qsthreshold], ...
    'Color', 'black', ...
    'LineStyle', '-', ...
    'LineWidth', 1, ...
    'Marker', 'none');
line(ax, [0 100], [fpthreshold fpthreshold], ...
    'Color', 'black', ...
    'LineStyle', ':', ...
    'LineWidth', 1, ...
    'Marker', 'none');
hold off;

%set(gca,'fontsize',labelfontsize);
set(ax,'fontsize',labelfontsize);

title(sprintf('QS:%s Measure:%s', qsmeasure, meas),'FontSize', labelfontsize);

legend(sprintf('TP  (%d/%.1f%%)', sum(tpidx),  100 * sum(tpidx)  / size(tpidx,  1)), ...
       sprintf('TN  (%d/%.1f%%)', sum(tnidx),  100 * sum(tnidx)  / size(tnidx,  1)), ...
       sprintf('FP1 (%d/%.1f%%)', sum(fp1idx), 100 * sum(fp1idx) / size(fp1idx, 1)), ...
       sprintf('FP2 (%d/%.1f%%)', sum(fp2idx), 100 * sum(fp2idx) / size(fp2idx, 1)), ...
       sprintf('FN  (%d/%.1f%%)', sum(fnidx),  100 * sum(fnidx)  / size(fnidx,  1)), ...
       'Location',  'eastoutside');

xlim(ax, [0 100]);
ylim(ax, [0 max(ydata)]);
xlabel('Percent Missing Points', 'FontSize', labelfontsize);
ylabel(sprintf('%s %% baseline', qsmeasure), 'FontSize', labelfontsize);

end

