function plotMeasurementDataForPaper(ax, days, mdata, colour, linestyle, linewidth, marker, markersize)

% plotMeasurementDataForPaper - plots the measurement data for a given measurement
% type

% plot measurement data
line(ax, days, mdata, ...
    'Color', colour, ...
    'LineStyle', linestyle, ...
    'LineWidth', linewidth, ...
    'Marker', marker, ...
    'MarkerSize', markersize,...
    'MarkerEdgeColor', colour, ...
    'MarkerFaceColor', colour);
    
end

