function axr = plottextModelCalibrationTable(p1, axl, modelcalibration, fold, plotsacross)

% plottextModelCalibrationTable - writes the model calibration results to a
% uicontrol on the figure


tabletitle = [  {sprintf('   BinRange    TrueLabels NbrInBin  Percentage')} ; ...
                {sprintf('-------------- ---------- --------  ----------')} ; ...
              ];

tabletext = tabletitle;
for a = 1:size(modelcalibration,1)
    rowstring = sprintf('%13s    %4.0f      %4.0f      %5.1f%%', modelcalibration.BinRange{a}, ...
        modelcalibration.TrueLabels(a), modelcalibration.NbrInBin(a), modelcalibration.Calibration(a));
    tabletext = [tabletext ; rowstring];
end
posvector = axl.Position;
posvector(1) = posvector(1) + (1/plotsacross);
plotnbr = 2 * (fold + 1);
axr = uicontrol('Parent', p1, ... 
                'Units', 'normalized', ...
                'OuterPosition', posvector, ...
                'Style', 'text', ...
                'FontName', 'FixedWidth', ...
                'FontSize', 6, ...
                'FontWeight', 'bold', ...
                'HorizontalAlignment', 'left', ...
                'String', tabletext);
          
end

