function plotMissingnessQSFcn(pmMSModelRes, pmMissPattIndex, pmMissPattQSPct, labels, qsthreshold, thresh, basemsresultsfile)

% plotMissingnessQSFcn - plots the quality scores vs the %age of missing
% data and also colour by correct vs incorrect result by the missingess
% classifier

basedir = setBaseDir();
plotsubfolder = sprintf('Plots/MissPatQS');
%mkdir(fullfile(basedir, plotsubfolder));

widthinch = 5;
heightinch = 5;
name = '';
plotsacross = 1;
plotsdown = 1;
labelfontsize = 8;
qsarray = {'AvgEPV', 'PRAUC', 'ROCAUC', 'Acc', 'PosAcc'};

tpidx = pmMSModelRes.Pred >= thresh & labels == 1;
fpidx = pmMSModelRes.Pred >= thresh & labels == 0;
tnidx = pmMSModelRes.Pred <  thresh & labels == 0;
fnidx = pmMSModelRes.Pred <  thresh & labels == 1;

tpcol = 'green';
fpcol = 'red';
tncol = [0.5 0.5 0.5];
fncol = 'blue';

%truepred = pmMSModelRes.Pred >= thresh;
xdata = pmMissPattIndex.MSPct;

transparency = 0.2;

for i = 1:size(qsarray, 2)
    qsmeasure = qsarray{i};
    baseplotname1 = sprintf('%s-QSC-%s', basemsresultsfile, qsmeasure);
    [f, p] = createFigureAndPanelForPaper(name, widthinch, heightinch);
    ax1 = subplot(plotsdown, plotsacross, 1, 'Parent', p);
    ydata = 100 * table2array(pmMissPattQSPct(:, {qsmeasure}));
    hold on;
    scatter(ax1, xdata(tpidx), ydata(tpidx), 20, ...
        'Marker', 'o', ...
        'MarkerEdgeColor', tpcol, ...
        'MarkerFaceColor', tpcol, ...
        'Marker', 'o', ...
        'MarkerEdgeAlpha', transparency, ...
        'MarkerFaceAlpha', transparency);
    scatter(ax1, xdata(tnidx), ydata(tnidx), 20, ...
        'MarkerEdgeColor', tncol, ...
        'MarkerFaceColor', tncol, ...
        'Marker', 'o', ...
        'MarkerEdgeAlpha', transparency, ...
        'MarkerFaceAlpha', transparency);
    scatter(ax1, xdata(fpidx), ydata(fpidx), 20, ...
        'MarkerEdgeColor', fpcol, ...
        'MarkerFaceColor', fpcol, ...
        'Marker', 'o', ...
        'MarkerEdgeAlpha', transparency, ...
        'MarkerFaceAlpha', transparency);
    scatter(ax1, xdata(fnidx), ydata(fnidx), 20, ...
        'MarkerEdgeColor', fncol, ...
        'MarkerFaceColor', fncol, ...
        'Marker', 'o', ...
        'MarkerEdgeAlpha', transparency, ...
        'MarkerFaceAlpha', transparency);
    line(ax1, [0 100], [qsthreshold qsthreshold], ...
        'Color', 'black', ...
        'LineStyle', '-', ...
        'LineWidth', 1, ...
        'Marker', 'none');
    hold off;
    set(gca,'fontsize',labelfontsize);
    title(qsmeasure,'FontSize', labelfontsize);
    if i == 1
        legend(sprintf('TP (%d)', sum(tpidx)), ...
               sprintf('TN (%d)', sum(tnidx)), ...
               sprintf('FP (%d)', sum(fpidx)), ...
               sprintf('FN (%d)', sum(fnidx)), ...
               'Location',  'east');
    end
    xlabel('Percent Missing Points', 'FontSize', labelfontsize);
    ylabel(sprintf('%s %% baseline', qsmeasure), 'FontSize', labelfontsize);
    
    basedir = setBaseDir();
    savePlotInDir(f, baseplotname1, basedir, plotsubfolder);
    close(f);
end 




end

