function plotRectangle(ax, xlb, xub, ylb, yub, linecol, linewidth, linestyle)

% plotRectangle - plots a rectangle on a set of axes

line(ax, [xlb xub], [ylb ylb], ...
    'Color', linecol, ...
    'LineStyle', linestyle, ...
    'LineWidth', linewidth, ...
    'Marker', 'none');

line(ax, [xlb xub], [yub yub], ...
    'Color', linecol, ...
    'LineStyle', linestyle, ...
    'LineWidth', linewidth, ...
    'Marker', 'none');

line(ax, [xlb xlb], [ylb yub], ...
    'Color', linecol, ...
    'LineStyle', linestyle, ...
    'LineWidth', linewidth, ...
    'Marker', 'none');

line(ax, [xub xub], [ylb yub], ...
    'Color', linecol, ...
    'LineStyle', linestyle, ...
    'LineWidth', linewidth, ...
    'Marker', 'none');


end

