function plotMissingnessQSFcn(pmMSModelRes, pmMissPattIndex, pmMissPattQSPct, labels, ...
    qsthreshold, fpthreshold, thresh, basemsresultsfile, plotsubfolder)

% plotMissingnessQSFcn - plots the quality scores vs the %age of missing
% data and also colour by correct vs incorrect result by the missingess
% classifier

widthinch = 7;
heightinch = 5;
name = '';
plotsacross = 1;
plotsdown = 1;
labelfontsize = 8;
qsarray = {'AvgEPV', 'PRAUC', 'ROCAUC', 'Acc', 'PosAcc'};

tpcol = 'green';
fp1col = [1.0 0.5 0];
fp2col = 'red';
tncol = [0.5 0.5 0.5];
fncol = 'blue';

%truepred = pmMSModelRes.Pred >= thresh;
xdata = pmMissPattIndex.MSPct;

transparency = 0.2;

for i = 1:size(qsarray, 2)
    
    qsmeasure = qsarray{i};
    
    tpidx  = pmMSModelRes.Pred >= thresh & labels == 1;
    fp1idx = pmMSModelRes.Pred >= thresh & labels == 0 & table2array(pmMissPattQSPct(:, {qsmeasure})) >= fpthreshold / 100;
    fp2idx = pmMSModelRes.Pred >= thresh & labels == 0 & table2array(pmMissPattQSPct(:, {qsmeasure})) <  fpthreshold / 100;
    tnidx  = pmMSModelRes.Pred <  thresh & labels == 0;
    fnidx  = pmMSModelRes.Pred <  thresh & labels == 1;
    
    baseplotname1 = sprintf('%sfp%d%s', basemsresultsfile, fpthreshold, qsmeasure);
    [f, p] = createFigureAndPanelForPaper(name, widthinch, heightinch);
    ax1 = subplot(plotsdown, plotsacross, 1, 'Parent', p);
    ydata = 100 * table2array(pmMissPattQSPct(:, {qsmeasure}));
    hold on;
    scatter(ax1, xdata(tpidx), ydata(tpidx), 20, ...
        'Marker', 'o', ...
        'MarkerEdgeColor', tpcol, ...
        'MarkerFaceColor', tpcol, ...
        'Marker', 'o', ...
        'MarkerEdgeAlpha', transparency, ...
        'MarkerFaceAlpha', transparency);
    scatter(ax1, xdata(tnidx), ydata(tnidx), 20, ...
        'MarkerEdgeColor', tncol, ...
        'MarkerFaceColor', tncol, ...
        'Marker', 'o', ...
        'MarkerEdgeAlpha', transparency, ...
        'MarkerFaceAlpha', transparency);
    scatter(ax1, xdata(fp1idx), ydata(fp1idx), 20, ...
        'MarkerEdgeColor', fp1col, ...
        'MarkerFaceColor', fp1col, ...
        'Marker', 'o', ...
        'MarkerEdgeAlpha', transparency, ...
        'MarkerFaceAlpha', transparency);
    scatter(ax1, xdata(fp2idx), ydata(fp2idx), 20, ...
        'MarkerEdgeColor', fp2col, ...
        'MarkerFaceColor', fp2col, ...
        'Marker', 'o', ...
        'MarkerEdgeAlpha', transparency, ...
        'MarkerFaceAlpha', transparency);
    scatter(ax1, xdata(fnidx), ydata(fnidx), 20, ...
        'MarkerEdgeColor', fncol, ...
        'MarkerFaceColor', fncol, ...
        'Marker', 'o', ...
        'MarkerEdgeAlpha', transparency, ...
        'MarkerFaceAlpha', transparency);
    line(ax1, [0 100], [qsthreshold qsthreshold], ...
        'Color', 'black', ...
        'LineStyle', '-', ...
        'LineWidth', 1, ...
        'Marker', 'none');
    line(ax1, [0 100], [fpthreshold fpthreshold], ...
        'Color', 'black', ...
        'LineStyle', ':', ...
        'LineWidth', 1, ...
        'Marker', 'none');
    hold off;
    set(gca,'fontsize',labelfontsize);
    title(qsmeasure,'FontSize', labelfontsize);
    legend(sprintf('TP  (%d)', sum(tpidx)), ...
           sprintf('TN  (%d)', sum(tnidx)), ...
           sprintf('FP1 (%d)', sum(fp1idx)), ...
           sprintf('FP2 (%d)', sum(fp2idx)), ...
           sprintf('FN  (%d)', sum(fnidx)), ...
           'Location',  'eastoutside');
    xlabel('Percent Missing Points', 'FontSize', labelfontsize);
    ylabel(sprintf('%s %% baseline', qsmeasure), 'FontSize', labelfontsize);
    
    basedir = setBaseDir();
    savePlotInDir(f, baseplotname1, basedir, plotsubfolder);
    close(f);
end 




end

