function plotPredVsDataComp(ax, lntmodelpred, lntdatacomp, colour)

% plotPredVsDataComp - produces a scatter plot of model prediction vs data
% completeness, colour coded by data completeness quintile, for either
% positive label examples or negative example days
    
hold on;
line(ax, lntdatacomp, lntmodelpred, ...
    'Color',           colour,  ...
    'LineStyle',       'none',  ...
    'LineWidth',       2,       ...
    'Marker',          'o',     ...
    'MarkerSize',      2,       ...
    'MarkerEdgeColor', colour,  ...
    'MarkerFaceColor', colour);

line(ax, [lntdatacomp(1), lntdatacomp(end)], [mean(lntmodelpred), mean(lntmodelpred)], ...
    'Color',           colour * 0.7,  ...
    'LineStyle',       '-',     ...
    'LineWidth',       2,       ...
    'Marker',          'none',  ...
    'MarkerSize',      2,       ...
    'MarkerEdgeColor', colour * 0.7,  ...
    'MarkerFaceColor', colour * 0.7);
hold off;
xl = [0 100];
xlim(ax, xl);
yl = [0   1];
ylim(ax, yl);



end

