function [vid, vname, validresponse] = selectPythVarName()

% selectPythVarName - select the name of the data structure to create the
% tabular version for python reconciliation

validresponse = true;

vname_array = {'pmPatients', ...
               'pmAntibiotics', ...
               'pmAMPred', ...
               'pmOverallStats', ...
               'pmPatientMeasStats', ...
               'pmRawDatacube', ...
               'pmFeatureIndex', ...
               'pmDataWinArray', ...
               'pmExABxElLabels', ...
               'pmNormDataWinArray', ...
               'pmInterpNormDataWinArray', ...
               'pmRawMeasWinArray', ...
               'pmVolWinArray', ...
               'pmPMeanWinArray', ...
               'pmMuIndex', ...
               'pmSigmaIndex', ...
               'pmNormFeatures', ...
               'pmNormFeatNames', ...
               'measures', ...
               'pmPatientSplit'};

nvars = size(vname_array, 2);

for i = 1:nvars          
    fprintf('%2d: %s\n', i, vname_array{i});
end

svid = input('Choose data structure to create tabular .xslx file for ? ', 's');

vid = str2double(svid);

if (isnan(vid) || vid < 1 || vid > nvars)
    fprintf('Invalid choice\n');
    validresponse = false;
    vid = 0;
    vname = '';
    return;
end

vname = vname_array{vid};

end
