function [mdayresstruct] = trainPredModel(modelver, mdayresstruct, features, labels, featnames, ...
                                nfeatures, fold, mmethod, lrval, ntrval, mlsval, mnsval, fvsval)

% trainPredModel - trains the predictive classifier model

rng(2); % for reproducibility

if ismember(modelver, {'vPM1'})
    mdayresstruct.Folds(fold).Model = compact(fitglm(features, labels, ...
        'linear', ...
        'Distribution', 'binomial', ...
        'Link', 'logit'));
elseif isequal(modelver, 'vPM4')
    mdayresstruct.Folds(fold).Model = compact(fitctree(features, labels, ...
        'Reproducible', true, ...
        'MinLeafSize', mlsval, ...
        'MaxNumSplits', mnsval, ...
        'NumVariablesToSample', floor(fvsval * nfeatures), ...
        'PredictorNames', featnames));
else
    %rng(2); % for reproducibility
    template = templateTree('Reproducible', true, ...
        'MinLeafSize', mlsval, ...
        'MaxNumSplits', mnsval, ...
        'NumVariablesToSample', floor(fvsval * nfeatures));   
                    
    if ismember(modelver, {'vPM11'})
        mdayresstruct.Folds(fold).Model = compact(fitcensemble(features, labels, ...
            'Method', mmethod, ...
            'NumLearningCycles', ntrval, ...
            'Learners', template, ...
            'LearnRate', lrval, ...
            'RatioToSmallest', [5, 1], ...
            'PredictorNames', featnames));
    elseif ismember(modelver, {'vPM13'})
        mdayresstruct.Folds(fold).Model = compact(fitcensemble(features, labels, ...
            'Method', mmethod, ...
            'NumLearningCycles', ntrval, ...
            'Learners', template, ...
            'LearnRate', lrval, ...
            'ScoreTransform', 'logit', ...
            'PredictorNames', featnames));
    else
        mdayresstruct.Folds(fold).Model = compact(fitcensemble(features, labels, ...
            'Method', mmethod, ...
            'NumLearningCycles', ntrval, ...
            'Learners', template, ...
            'PredictorNames', featnames));
    end
end

end

